# Generated by Django 4.2.3 on 2023-09-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products2', to='app_orders.order'),
        ),
    ]
