# Generated by Django 4.2.3 on 2023-09-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_productinstance_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='number_of_purchases',
            field=models.PositiveIntegerField(blank=True, default=True, null=True, verbose_name='Количество покупок'),
        ),
    ]
