# Generated by Django 4.2.3 on 2023-09-24 11:33

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, default='images/no_image.jpg', null=True, upload_to='images/images_avatars/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Альтернативная строка изображения аватара')),
            ],
            options={
                'verbose_name': 'Изображение аватара',
                'verbose_name_plural': 'Изображения аватара',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL пользователя')),
                ('fullName', models.CharField(default=None, max_length=150, null=True, verbose_name='Ф.И.О.')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile2', to='app_users.avatarsimages', verbose_name='Аватар пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ('user',),
            },
        ),
    ]
