# Generated by Django 4.2.3 on 2023-09-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarsimages',
            name='src',
            field=models.URLField(blank=True, default='images/no_image.jpeg', null=True, verbose_name='Изображение'),
        ),
    ]
