# Generated by Django 4.2.3 on 2023-09-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_avatarsimages_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarsimages',
            name='src',
            field=models.ImageField(blank=True, default='images/no_image.jpeg', null=True, upload_to='images/images_avatars/', verbose_name='Изображение'),
        ),
    ]
